import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import { ReduxProviders } from './reduxProvider'
import Navbar from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import { Box } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body>
      <ReduxProviders>
      <Providers>
      <Navbar />  
      <Box minH={{ base: "calc(100vh - 270px)", md: "calc(100vh - 228px)" }} display="flex" justifyContent="center" alignItems="center">
        {children}
        </Box> 
        <Footer />
        </Providers>
        </ReduxProviders>
        </body>
    </html>
  )
}
